server:
  port: 5000
  address: 0.0.0.0

spring:
  application:
    name: event-notification-system
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC

logging:
  level:
    com.sprih.notification: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

notification:
  processing:
    email-delay: 5000
    sms-delay: 3000
    push-delay: 2000
    failure-rate: 0.1
  callback:
    timeout: 5000
    retries: 3
  shutdown:
    timeout: 30000
